name: notes_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.5.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
